// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2NlbmcCi0RkQwA1MEKE7TXcsAq5BUcMM',
    appId: '1:622073935251:web:696bd7888b49c3e10e2466',
    messagingSenderId: '622073935251',
    projectId: 'plantify-ef52a',
    authDomain: 'plantify-ef52a.firebaseapp.com',
    databaseURL: 'https://plantify-ef52a-default-rtdb.firebaseio.com/',
    storageBucket: 'plantify-ef52a.appspot.com',
    measurementId: 'G-214231MSZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdj5qxtqOGLxn5V4BqTNtUYa7lpekpr5M',
    appId: '1:622073935251:android:bed0fccc2c0f735c0e2466',
    messagingSenderId: '622073935251',
    projectId: 'plantify-ef52a',
    storageBucket: 'plantify-ef52a.appspot.com',
    databaseURL: 'https://plantify-ef52a-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8x7eTzr4CbeyK-FQvSFvoLWK0w83hzbU',
    appId: '1:622073935251:ios:09bb30d344d3332e0e2466',
    messagingSenderId: '622073935251',
    projectId: 'plantify-ef52a',
    storageBucket: 'plantify-ef52a.appspot.com',
    iosBundleId: 'com.example.plantify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8x7eTzr4CbeyK-FQvSFvoLWK0w83hzbU',
    appId: '1:622073935251:ios:8194b82146204a210e2466',
    messagingSenderId: '622073935251',
    projectId: 'plantify-ef52a',
    storageBucket: 'plantify-ef52a.appspot.com',
    iosBundleId: 'com.example.plantify.RunnerTests',
  );
}
